### ISSUE TITLE
Can't load the HF model

### ISSUE THREAD

**Issue by vfragoso** [mbzuai-oryx/LLaVA-pp#10]
Thanks for the good work! I tried to load the model via HF, but I am getting this error:

![image](https://github.com/mbzuai-oryx/LLaVA-pp/assets/565559/c8dcac9f-1e04-40e8-9845-48e874439e9f)

Any hint as to how to solve this?

Thanks!

**Comment by mmaaz60** [comment]
Hi @vfragoso,

Thank you for your interest in our work. Unfortunately, the vision version of Phi-3 is not yet added to the transformers and you have to use our provided code to correctly load the model.

Please try using our [Hugging Face Demo](https://huggingface.co/collections/MBZUAI/llava-662b38b972e3e3e4d8f821bb). It will be definitely helpful. Thank You.
