### ISSUE TITLE
Exactly same as our study! Interesting!

### ISSUE THREAD

**Issue by mu-cai** [mbzuai-oryx/LLaVA-pp#13]
Great work! It is pretty interesting that last week, we did an exactly same study, 

https://github.com/WisconsinAIVision/ViP-LLaVA/blob/main/docs/study_llm_backbone.md

Our same empirical evaluation findings demonstrate the correctness of each other’s implementation. haha

Mu Cai

**Comment by Isaachhh** [comment]
We Bunny team also provide Bunny-Llama-3-8B-V and Bunny-Phi-3-V with much better performance~

https://github.com/BAAI-DCAI/Bunny

**Comment by mmaaz60** [comment]
Hi @mu-cai, @Isaachhh,

Its great to see such open-source efforts adapting recently released LLMs. Congratulations on your achievements!
