### ISSUE TITLE
Clarification of ScienceQA score

### ISSUE THREAD

**Issue by Isaachhh** [mbzuai-oryx/LLaVA-pp#2]
I notice that your model achieve ~80 on ScienceQA. I wonder whether you report total accuracy other than image accuracy, because LLaVA reports only image accuracy (66.8 for 7B and 71.6 for 13B).
Thanks!

**Comment by mmaaz60** [comment]
Hi @Isaachhh,

Thank you for pointing it out, and apologies for any confusion it may have caused. We have updated the main results and added some additional models as well. I am pasting the table below for your reference.

![image](https://github.com/mbzuai-oryx/LLaVA-pp/assets/55104795/2d074c87-5339-477b-9439-6de7b22fd46e)

Let us know if you have any questions. Thank You

**Comment by Isaachhh** [comment]
Thank you!
